### ISSUE TITLE
Port Protocol Not Set on Deployment Ports

### ISSUE THREAD

**Issue by mehdimas** [lightbend/reactive-cli#192]
Protocol information is not being set on the ports for a deployment. I observe that when there is a port of type UDP, the output yaml does not include the protocol field. This is incorrect because Kubernetes will default to TCP.

Incorrect Output:
```
apiVersion: "apps/v1beta2"
kind: Deployment
...
         ports:
            - containerPort: 10000
              name: "akka-remote"
            - containerPort: 10001
              name: "akka-mgmt-http"
            - containerPort: 9001
              name: "tcp"
            - containerPort: 9002
              name: "udp"
...
```

Expected Output:
```
apiVersion: "apps/v1beta2"
kind: Deployment
...
         ports:
            - containerPort: 10000
              name: "akka-remote"
              protocol: TCP
            - containerPort: 10001
              name: "akka-mgmt-http"
              protocol: TCP
            - containerPort: 9001
              name: "tcp"
              protocol: TCP
            - containerPort: 9002
              name: "udp"
              protocol: UDP
...
```
