### ISSUE TITLE
generate-all does not generate ingress

### ISSUE THREAD

**Issue by IntelligyScience** [lightbend/reactive-cli#204]
Version 1.6.* generates an ingress. After update to version 1.7.0 no ingress is generated! 

```
rp generate-kubernetes-resources "docker-registry...../communicationdepartment-impl:0.9-SNAPSHOT"  \
      --pod-controller-replicas 3 --generate-ingress --deployment-type rolling \
      --registry-username andre --registry-password ********** \
      --pod-controller-image-pull-policy Always --ingress-annotation kubernetes.io/ingress.class=traefik \
      --external-service "cas_native=_cql._tcp.cassandra.avalon.svc.cluster.local" \
      --external-service "kafka_native=kafka.avalon.svc.cluster.local:9092" \
      --namespace avalon --env JAVA_OPTS="-Dplay.http.secret.key=****** -Dplay.filters.hosts.allowed.0=."
```
generates nothing!

```
rp generate-kubernetes-resources "docker-registry...../communicationdepartment-impl:0.9-SNAPSHOT"  \
      --pod-controller-replicas 3 --generate-all --deployment-type rolling \
      --registry-username andre --registry-password ********** \
      --pod-controller-image-pull-policy Always --ingress-annotation kubernetes.io/ingress.class=traefik \
      --external-service "cas_native=_cql._tcp.cassandra.avalon.svc.cluster.local" \
      --external-service "kafka_native=kafka.avalon.svc.cluster.local:9092" \
      --namespace avalon --env JAVA_OPTS="-Dplay.http.secret.key=****** -Dplay.filters.hosts.allowed.0=."
```

generates:

```yaml
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: communicationdepartment
  labels:
    app: communicationdepartment
    appNameVersion: "communicationdepartment-v0-9-snapshot"
    "akka.lightbend.com/service-name": communicationdepartment
  namespace: avalon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: communicationdepartment
  template:
    metadata:
      labels:
        app: communicationdepartment
        appNameVersion: "communicationdepartment-v0-9-snapshot"
        "akka.lightbend.com/service-name": communicationdepartment
    spec:
      restartPolicy: Always
      containers:
        - name: communicationdepartment
          image: "docker-registry.****/communicationdepartment-impl:0.9-SNAPSHOT"
          imagePullPolicy: Always
          env:
            - name: "JAVA_OPTS"
              value: "-Dplay.http.secret.key=*****"
            - name: "RP_APP_NAME"
              value: communicationDepartment
            - name: "RP_APP_TYPE"
              value: lagom
            - name: "RP_APP_VERSION"
              value: "0.9-SNAPSHOT"
            - name: "RP_DYN_JAVA_OPTS"
              value: "-Dakka.discovery.kubernetes-api.pod-namespace=$RP_NAMESPACE"
            - name: "RP_JAVA_OPTS"
              value: "-Dconfig.resource=rp-application.conf -Dakka.management.cluster.bootstrap.contact-point-discovery.discovery-method=kubernetes-api -Dakka.management.cluster.bootstrap.contact-point-discovery.port-name=management -Dakka.management.cluster.bootstrap.contact-point-discovery.effective-name=communicationdepartment -Dakka.discovery.kubernetes-api.pod-label-selector=akka.lightbend.com/service-name=%s -Dakka.management.cluster.bootstrap.contact-point-discovery.required-contact-point-nr=3 -Dplay.server.pidfile.path=/dev/null -Dcom.lightbend.platform-tooling.service-discovery.external-service-addresses.cas_native.0=_cql._tcp.cassandra.avalon.svc.cluster.local -Dcom.lightbend.platform-tooling.service-discovery.external-service-addresses.kafka_native.0=kafka.avalon.svc.cluster.local:9092"
            - name: "RP_KUBERNETES_POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_KUBERNETES_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: "RP_MODULES"
              value: "akka-cluster-bootstrapping,akka-management,common,service-discovery,status"
            - name: "RP_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "RP_PLATFORM"
              value: kubernetes
          ports:
            - containerPort: 10000
              name: http
            - containerPort: 2552
              name: remoting
            - containerPort: 8558
              name: management
          volumeMounts: []
          command:
            - "/opt/docker/bin/rp-start"
          args:
            - "bin/communicationdepartment-impl"
          readinessProbe:
            httpGet:
              path: "/platform-tooling/ready"
              port: management
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/platform-tooling/healthy"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 60
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: communicationdepartment
  name: communicationdepartment
  namespace: avalon
spec:
  ports:
    - name: http
      port: 10000
      protocol: TCP
      targetPort: 10000
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: communicationdepartment
```

**Comment by IntelligyScience** [comment]
the other µservice generates an ingress controller. The same rp command

```
---
apiVersion: "extensions/v1beta1"
kind: Ingress
metadata:
  name: workermanagement
  annotations:
    "kubernetes.io/ingress.class": traefik
  namespace: avalon
spec:
  rules:
    - http:
        paths:
          - path: "/api/global-permission"
            backend:
              serviceName: workermanagement
              servicePort: 10000
          - path: "/api/worker"
            backend:
              serviceName: workermanagement
              servicePort: 10000

```
